# Generated by Django 4.2.3 on 2023-08-04 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='sport',
            field=models.CharField(blank=True, choices=[('foot', 'football'), ('bask', 'basketball'), ('voll', 'volleyball'), ('hock', 'hockey'), ('athl', 'athletics'), ('divi', 'diving'), ('biat', 'biathlon'), ('boxi', 'boxing'), ('ches', 'chess')], max_length=4, null=True, verbose_name='sport'),
        ),
    ]
