# Generated by Django 4.2.3 on 2023-08-05 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_profile_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='sport',
            field=models.CharField(blank=True, choices=[('football', 'football'), ('basketball', 'basketball'), ('volleyball', 'volleyball'), ('hockey', 'hockey'), ('athletics', 'athletics'), ('diving', 'diving'), ('biathlon', 'biathlon'), ('boxing', 'boxing'), ('chess', 'chess')], default='football', max_length=16, null=True),
        ),
    ]
