# Generated by Django 4.2.3 on 2023-08-13 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_profile_sport'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='tg_link',
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
